config/routes.rb
Rails.application.routes.draw do
  # get 'spa/index'
  # get 'pages/index'
  # get 'app', to: 'spa#index'
  # get 'app/*path', to: 'spa#index'

  root 'page#index'
  resources :urls
  get ':short_path', to: 'redirect#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original, presence: true, uniqueness: true, url: true
  validates :shortened, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  around_action :switch_locale

  def index
    @urls = Url.all
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/redirect_controller.rb
# frozen_string_literal: true

class RedirectController < ApplicationController
  def show
    url = Url.find_by!(shortened: params[:short_path])
    redirect_to url.original
  end
end

app/controllers/spa_controller.rb
class SpaController < ApplicationController
  layout 'spa'
  def index
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    url = Shortener.call(url_params[:original])
    render json: { url: url, errors: url.errors },
           status: (url&.valid? ? :created : :unprocessable_entity)
  end

  def destroy
    @url = Url.find_by(id: params[:id])
    if @url.destroy
      redirect_to root_path
    end
  end

  private

  def url_params
    params.require(:url).permit(:original)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spa_helper.rb
module SpaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<%= react_component 'Form', locale: params[:locale] %>


<table id="style-3" class="table style-3" data-ordering="false">
  <thead>
    <tr>
      <th>Original Url</th>
      <th>Shortned Url</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.original%></td>
        <td><%= request.original_url +  url.shortened%></td>
        <td><%= link_to 'Destroy', url_path(url.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>